### ISSUE TITLE
Cannot read property 'statusCode' of null

### ISSUE THREAD

**Issue by alexknipfer** [Microsoft/BotBuilder-Azure#78]
Anybody else seeing the following error or know what could possibly be causing it? It happens regularly, but no steps to reproduce.

```
/Users/alexanderknipfer/Projects/chronos/node_modules/botbuilder-azure/lib/AzureTableClient.js:38
            if (response.statusCode == Consts.HttpStatusCodes.NotFound) {
                         ^

TypeError: Cannot read property 'statusCode' of null
    at /Users/alexanderknipfer/Projects/chronos/node_modules/botbuilder-azure/lib/AzureTableClient.js:38:26
    at finalCallback (/Users/alexanderknipfer/Projects/chronos/node_modules/botbuilder-azure/node_modules/azure-storage/lib/services/table/tableservice.js:1297:9)
    at /Users/alexanderknipfer/Projects/chronos/node_modules/botbuilder-azure/node_modules/azure-storage/lib/common/filters/retrypolicyfilter.js:178:13
    at /Users/alexanderknipfer/Projects/chronos/node_modules/botbuilder-azure/node_modules/azure-storage/lib/common/services/storageserviceclient.js:756:17
    at /Users/alexanderknipfer/Projects/chronos/node_modules/botbuilder-azure/node_modules/azure-storage/lib/common/services/storageserviceclient.js:959:11
    at /Users/alexanderknipfer/Projects/chronos/node_modules/botbuilder-azure/node_modules/azure-storage/lib/common/services/storageserviceclient.js:755:15
    at processResponseCallback (/Users/alexanderknipfer/Projects/chronos/node_modules/botbuilder-azure/node_modules/azure-storage/lib/services/table/tableservice.js:1301:5)
    at Request.processResponseCallback [as _callback] (/Users/alexanderknipfer/Projects/chronos/node_modules/botbuilder-azure/node_modules/azure-storage/lib/common/services/storageserviceclient.js:316:13)
    at self.callback (/Users/alexanderknipfer/Projects/chronos/node_modules/botbuilder-azure/node_modules/request/request.js:187:22)
    at Request.emit (events.js:180:13)
```

**Comment by JasonSowers** [comment]
Are you able to share your code so we can take a look?

**Comment by alexknipfer** [comment]
@JasonSowers Sorry I never got back to responding. It seems to have sorted itself out so I closed the issue, will report back if I see it again.
