### ISSUE TITLE
az bot create fails when --storage/-s switch is used

### ISSUE THREAD

**Issue by drub0y** [microsoft/BotBuilder-Azure#97]
I was trying to create a new bot with `az bot create`, but wanted to link to an already existing storage and whenever I tried this it would fail with the following stack trace:

```cli
local variable 'site_name' referenced before assignment
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\knack\cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qw7dqhq0\azure-cli-core\azure\cli\core\commands\__init__.py", line 372, in execute
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qw7dqhq0\azure-cli-core\azure\cli\core\commands\__init__.py", line 346, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qw7dqhq0\azure-cli-core\azure\cli\core\commands\__init__.py", line 182, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qw7dqhq0\azure-cli-core\azure\cli\core\__init__.py", line 436, in default_command_handler
  File "C:\Users\drmarsh\.azure\cliextensions\botservice\azext_bot\custom.py", line 97, in create
    storageAccountName, location, sku_name, appInsightsLocation, language, version)
  File "C:\Users\drmarsh\.azure\cliextensions\botservice\azext_bot\custom.py", line 177, in create_app
    "siteName": site_name,
UnboundLocalError: local variable 'site_name' referenced before assignment
```

**Comment by xxlennxx** [comment]
Same issue here...could you solve it?

**Comment by EricDahlvang** [comment]
Hey @drub0y 

This is the BotBuilder-Azure repository.  Please close this and move to the tools repo: https://github.com/Microsoft/botbuilder-tools/issues

**Comment by cleemullins** [comment]
Thank you for opening an issue against the BotBuilder-Azure repo. As part of the Bot Framework v4 release, we’ve moved all the Azure related work to the [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
